- name: Install software
  apt: name={{item}}
  with_items: 
      - apache2
  allow_unauthenticated: yes
  force: yes
  update_cache: yes
  state: latest
  install_recommends: no
- name: start apache service
  systemd:
    name: apache2
    state: started
- name: copy code to server
  copy:
   src: web/
   dest: /var/www/html
   owner: root
   group: root
