---
- hosts: couchdb
  become: yes
  gather_facts: true
  tasks: 
  - name: Format disk
    filesystem: 
     fstype: ext4
     dev: /dev/vdc
  - name: Creates directory for volume
    file: 
     path: /home/ubuntu/cloud
     state: directory
     mode: 0777
  - name: Creates directory for volume
    file: 
     path: /home/ubuntu/hdfs
     state: directory
     mode: 0777
  - name: Mount volume to directory
    mount: 
     path: /home/ubuntu/cloud
     src: /dev/vdb
     fstype: ext4
     state: unmounted
  - name: Mount volume to directory
    mount: 
     path: /home/ubuntu/cloud
     src: /dev/vdc
     fstype: ext4
     state: mounted
  - name: add apt-repository for java
    apt_repository: 
     repo: 'ppa:webupd8team/java'
  - name: accept oracle license
    debconf:
     name: oracle-java8-installer
     question: shared/accepted-oracle-license-v1-1
     value: 'true'
     vtype: select
  - name: Install software
    apt: name={{item}}
    with_items: 
      - libmozjs185-dev
      - libicu-dev
      - libcurl4-openssl-dev
      - build-essential 
      - pkg-config
      - python3-pip
      - screen
      - curl
      - erlang
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
      - git
    allow_unauthenticated: yes
    force: yes
    update_cache: yes
    state: latest
    install_recommends: no
  - name: install pip nltk
    command: pip3 install nltk
  - name: install pip requests
    command: pip3 install requests
  - name: install pip tweepy
    command: pip3 install tweepy
  - name: install pip couchdb
    command: pip3 install couchdb
  - name: install pip profanity
    command: pip3 install profanity
  - name: install pip vaderSentiment
    command: pip3 install vaderSentiment
  - name: install nltk wordnet
    command: python3 -m nltk.downloader wordnet
  - name: install nltk punkt
    command: python3 -m nltk.downloader punkt 
#  - name: stop CouchDB Service
#    systemd:
#        name: couchdb
#        state: stopped
  - name: download couchdb
    get_url:
      url: https://dist.apache.org/repos/dist/release/couchdb/source/2.1.1/apache-couchdb-2.1.1.tar.gz
      dest: /opt
  - name: unpack source code
    unarchive: 
      src: /opt/apache-couchdb-2.1.1.tar.gz
      dest: /opt
      remote_src: yes
  - name: execute configure
    command: chdir=/opt/apache-couchdb-2.1.1 ./configure
  - name: make release
    make: 
      chdir: /opt/apache-couchdb-2.1.1
      target: release
  - name: copy couchdb to directory
    command: cp -R /opt/apache-couchdb-2.1.1/rel/couchdb /home/ubuntu/cloud
  - name: set node name for couchdb
    replace: 
      dest: /home/ubuntu/cloud/couchdb/etc/vm.args
      regexp: '-name couchdb@127.0.0.1$'
      replace: '-name couchdb@{{ansible_default_ipv4.address}}'
  - name: change cookie
    replace: 
      dest: /home/ubuntu/cloud/couchdb/etc/vm.args
      regexp: '^-setcookie monster$'
      replace: '-setcookie couchdb_cluster'
  - name: change bind address
    lineinfile: 
      dest: /home/ubuntu/cloud/couchdb/etc/local.ini
      insertafter: '^\[chttpd\]$'
      line: 'bind_address = 0.0.0.0'
  - name: change cluster node address
    lineinfile:
     dest: /home/ubuntu/cloud/couchdb/etc/local.ini
     insertafter: '^\[httpd\]$'
     line: 'bind_address = 0.0.0.0'
  - name: add user
    lineinfile:
     dest: /home/ubuntu/cloud/couchdb/etc/local.ini
     insertafter: '^\[admins\]$'
     line: 'admin=admin' 
  - name: Install CouchDB Service
    copy:
        src: ./couchdb.service
        dest: /etc/systemd/system/couchdb.service
        owner: root
        group: root
  - name: Enable CouchDB Service
    systemd:
        daemon-reload: yes
        name: couchdb
        enabled: yes
  - name: Start CouchDB Service
    systemd:
        name: couchdb
        state: started 
  
